/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateCartRequest,
  UpdateCartRequest
} from '.././model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export type updateCartItemResponse200 = {
  data: void
  status: 200
}
    
export type updateCartItemResponseSuccess = (updateCartItemResponse200) & {
  headers: Headers;
};
;

export type updateCartItemResponse = (updateCartItemResponseSuccess)

export const getUpdateCartItemUrl = (productId: number,) => {


  

  return `/api/myCart/products/${productId}`
}

export const updateCartItem = async (productId: number,
    updateCartRequest: UpdateCartRequest, options?: RequestInit): Promise<updateCartItemResponse> => {
  
  const res = await fetch(getUpdateCartItemUrl(productId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCartRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateCartItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateCartItemResponse
}




export const getUpdateCartItemMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCartItem>>, TError,{productId: number;data: UpdateCartRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateCartItem>>, TError,{productId: number;data: UpdateCartRequest}, TContext> => {

const mutationKey = ['updateCartItem'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCartItem>>, {productId: number;data: UpdateCartRequest}> = (props) => {
          const {productId,data} = props ?? {};

          return  updateCartItem(productId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCartItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateCartItem>>>
    export type UpdateCartItemMutationBody = UpdateCartRequest
    export type UpdateCartItemMutationError = unknown

    export const useUpdateCartItem = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCartItem>>, TError,{productId: number;data: UpdateCartRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCartItem>>,
        TError,
        {productId: number;data: UpdateCartRequest},
        TContext
      > => {
      return useMutation(getUpdateCartItemMutationOptions(options), queryClient);
    }
    export type deleteCartItemResponse204 = {
  data: void
  status: 204
}
    
export type deleteCartItemResponseSuccess = (deleteCartItemResponse204) & {
  headers: Headers;
};
;

export type deleteCartItemResponse = (deleteCartItemResponseSuccess)

export const getDeleteCartItemUrl = (productId: number,) => {


  

  return `/api/myCart/products/${productId}`
}

export const deleteCartItem = async (productId: number, options?: RequestInit): Promise<deleteCartItemResponse> => {
  
  const res = await fetch(getDeleteCartItemUrl(productId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteCartItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteCartItemResponse
}




export const getDeleteCartItemMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCartItem>>, TError,{productId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCartItem>>, TError,{productId: number}, TContext> => {

const mutationKey = ['deleteCartItem'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCartItem>>, {productId: number}> = (props) => {
          const {productId} = props ?? {};

          return  deleteCartItem(productId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCartItemMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCartItem>>>
    
    export type DeleteCartItemMutationError = unknown

    export const useDeleteCartItem = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCartItem>>, TError,{productId: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCartItem>>,
        TError,
        {productId: number},
        TContext
      > => {
      return useMutation(getDeleteCartItemMutationOptions(options), queryClient);
    }
    export type createCartItemResponse201 = {
  data: void
  status: 201
}
    
export type createCartItemResponseSuccess = (createCartItemResponse201) & {
  headers: Headers;
};
;

export type createCartItemResponse = (createCartItemResponseSuccess)

export const getCreateCartItemUrl = () => {


  

  return `/api/myCart/products`
}

export const createCartItem = async (createCartRequest: CreateCartRequest, options?: RequestInit): Promise<createCartItemResponse> => {
  
  const res = await fetch(getCreateCartItemUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCartRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createCartItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createCartItemResponse
}




export const getCreateCartItemMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCartItem>>, TError,{data: CreateCartRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createCartItem>>, TError,{data: CreateCartRequest}, TContext> => {

const mutationKey = ['createCartItem'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCartItem>>, {data: CreateCartRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCartItem(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCartItemMutationResult = NonNullable<Awaited<ReturnType<typeof createCartItem>>>
    export type CreateCartItemMutationBody = CreateCartRequest
    export type CreateCartItemMutationError = unknown

    export const useCreateCartItem = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCartItem>>, TError,{data: CreateCartRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCartItem>>,
        TError,
        {data: CreateCartRequest},
        TContext
      > => {
      return useMutation(getCreateCartItemMutationOptions(options), queryClient);
    }
    export type getMyCartResponse200 = {
  data: Blob
  status: 200
}
    
export type getMyCartResponseSuccess = (getMyCartResponse200) & {
  headers: Headers;
};
;

export type getMyCartResponse = (getMyCartResponseSuccess)

export const getGetMyCartUrl = () => {


  

  return `/api/myCart`
}

export const getMyCart = async ( options?: RequestInit): Promise<getMyCartResponse> => {
  
  const res = await fetch(getGetMyCartUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMyCartResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMyCartResponse
}





export const getGetMyCartQueryKey = () => {
    return [
    `/api/myCart`
    ] as const;
    }

    
export const getGetMyCartQueryOptions = <TData = Awaited<ReturnType<typeof getMyCart>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyCart>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyCartQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyCart>>> = ({ signal }) => getMyCart({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyCart>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyCartQueryResult = NonNullable<Awaited<ReturnType<typeof getMyCart>>>
export type GetMyCartQueryError = unknown


export function useGetMyCart<TData = Awaited<ReturnType<typeof getMyCart>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyCart>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyCart>>,
          TError,
          Awaited<ReturnType<typeof getMyCart>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyCart<TData = Awaited<ReturnType<typeof getMyCart>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyCart>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyCart>>,
          TError,
          Awaited<ReturnType<typeof getMyCart>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyCart<TData = Awaited<ReturnType<typeof getMyCart>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyCart>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMyCart<TData = Awaited<ReturnType<typeof getMyCart>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyCart>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyCartQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type deleteCartResponse204 = {
  data: void
  status: 204
}
    
export type deleteCartResponseSuccess = (deleteCartResponse204) & {
  headers: Headers;
};
;

export type deleteCartResponse = (deleteCartResponseSuccess)

export const getDeleteCartUrl = () => {


  

  return `/api/myCart`
}

export const deleteCart = async ( options?: RequestInit): Promise<deleteCartResponse> => {
  
  const res = await fetch(getDeleteCartUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteCartResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteCartResponse
}




export const getDeleteCartMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCart>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCart>>, TError,void, TContext> => {

const mutationKey = ['deleteCart'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCart>>, void> = () => {
          

          return  deleteCart(fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCartMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCart>>>
    
    export type DeleteCartMutationError = unknown

    export const useDeleteCart = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCart>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCart>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeleteCartMutationOptions(options), queryClient);
    }
    