/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductResponse } from './productResponse';

export interface OrderItemResponse {
  id?: number;
  product?: ProductResponse;
  quantity?: number;
  price?: number;
}
