/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Product {
  id?: number;
  brand?: string;
  productName?: string;
  price?: number;
  stock?: number;
  image?: string;
}
