/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ProductRequest {
  /**
   * @minLength 2
   * @maxLength 50
   */
  brand: string;
  productName: string;
  price?: number;
  stock?: number;
  image?: string;
}
