/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateOrderStatusStatus = typeof UpdateOrderStatusStatus[keyof typeof UpdateOrderStatusStatus];


export const UpdateOrderStatusStatus = {
  PLACED: 'PLACED',
  PROCESSING: 'PROCESSING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
} as const;
